### ISSUE TITLE
[BUG] Notification menu does not open

### ISSUE THREAD

**Issue by Veicm** [mylinuxforwork/dotfiles#661]
### Describe the bug

When I click on the bell picture on waybar, the notification menu does not open.

### Steps to reproduce

1. Click on the bell picture on waybar
2. see error (nothing happen)

### Expected behavior

The menu which I sawed on discord and GitHub should open.

### Screenshots

This is the menu which don't open:

![Image](https://github.com/user-attachments/assets/1b3da8b4-b62a-458f-83b4-9b3f3012e56f)

### Distribution

Arch Linux

### Additional context

I have installed the Beta version a few minutes ago.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mylinuxforwork** [comment]
@Veicm Can you check that swaync has been installed successfully? With yay -S swaync

Then reboot and try again.

**Comment by dwilliam62** [comment]
i just filed an issue on this.  Please go to  ~/.config/ml4w/settings    Edit notifications.sh   Check to see if the file has `dunst` in it.  If so comment that out with a `#`  sign save and at the CLI do `pkill dunst`.   Logout and back in.   The notification center should now work.

**Comment by eljejer** [comment]
> [@Veicm](https://github.com/Veicm) Can you check that swaync has been installed successfully? With yay -S swaync
> 
> Then reboot and try again.

swaync-0.10.1-3 is up to date in my case

Also, dunst gives critical error:

```
$ /home/eljejer : dunst
MESSAGE: Using legacy offset syntax NxN, you should switch to the new syntax (N, N)
WARNING: Progress bar corner radius clamped to half of progress bar height (5)
CRITICAL: [dbus_cb_name_lost:1378] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'mako' with PID '11463'.

╭─eljejer   󰉖 ~
╰─ ❯❯  
```

**Comment by eljejer** [comment]
> i just filed an issue on this. Please go to ~/.config/ml4w/settings Edit notifications.sh Check to see if the file has `dunst` in it. If so comment that out with a `#` sign save and at the CLI do `pkill dunst`. Logout and back in. The notification center should now work.
> 
> `~/.config/ml4w/settings/notifications.sh `

After this change, clicking the 'bell' in waybar still does nothing. I do get notifications however.

**Comment by mylinuxforwork** [comment]
Ok. Can you check the file .config/ml4w/settings/notification.sh

Is there dunst in? If yes, replace it with swaync

**Comment by eljejer** [comment]
> Ok. Can you check the file .config/ml4w/settings/notification.sh
> 
> Is there dunst in? If yes, replace it with swaync and reboot.

Indeed, this script file contains only 'dunst'
Changing this into 'swaync' and a reboot resolved the issue
